apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    project: msp-invoice
    bi: keycloak
    app: keycloak 
    env: dev
    tier: backend
spec:
  type: NodePort
  ports:
  - name: wab-client
    port: 8094
    targetPort: 8094
    nodePort: 30007
    protocol: TCP
  selector:
    project: msp-invoice
    bi: keycloak
    app: keycloak 
    env: dev
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:12.0.4
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8095
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8085