apiVersion: v1
kind: Service
metadata:
  labels:
    project: msp-invoice
    app: clickhouse 
    env: dev
    tier: database
  name: clickhouse
spec:
  ports:
    - name: web-client
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: native-client
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    project: msp-invoice
    app: clickhouse 
    env: dev
    tier: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  labels:
    project: msp-invoice
    app: clickhouse 
    env: dev
    tier: database
spec:
  selector:
    matchLabels:
      project: msp-invoice
      app: clickhouse 
      env: dev
      tier: database
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: msp-invoice
        app: clickhouse 
        env: dev
        tier: database
    spec:
      volumes:
        - name: msp-invoice-pv
          hostPath: 
            path: /tmp
            type: DirectoryOrCreate
      containers:
        - name: clickhouse-server
          image: 'yandex/clickhouse-server:latest'
          imagePullPolicy: Always
          ports:
            - name: web-client
              containerPort: 8123
              protocol: TCP
            - name: native-client
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: msp-invoice-pv
              mountPath: /var/lib/clickhouse
              subPath: clickhouse