apiVersion: v1
kind: Service
metadata:
  labels:
    project: msp-invoice
    bi: redash
    app: email
    env: dev
    tier: backend
  name: redashemail
spec:
  ports:
    - name: email-service-port
      port: 1080
      targetPort: 80
  selector:
    project: msp-invoice
    bi: redash
    app: email
    env: dev
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    project: msp-invoice
    bi: redash
    app: email
    env: dev
    tier: backend
  name: redashemail
spec:
  replicas: 1
  selector:
    matchLabels:
      project: msp-invoice
      bi: redash
      app: email
      env: dev
      tier: backend
  template:
    metadata:
      labels:
        project: msp-invoice
        bi: redash
        app: email
        env: dev
        tier: backend
    spec:
      containers:    
        - image: djfarrelly/maildev          
          name: email
          ports:
            - containerPort: 80