apiVersion: v1
kind: Service
metadata:
  name: redashredis
  labels:
    project: msp-invoice
    bi: redash
    app: redis 
    env: dev
    tier: database
spec:
  type: NodePort
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
      nodePort: 30637
      protocol: TCP
  selector:
      project: msp-invoice
      bi: redash
      app: redis 
      env: dev
      tier: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: msp-invoice
    bi: redash
    app: redis 
    env: dev
    tier: database
  name: redashredis
spec:
  replicas: 1
  selector:
    matchLabels:
      project: msp-invoice
      bi: redash
      app: redis 
      env: dev
      tier: database
  template:
    metadata:
      labels:
        project: msp-invoice
        bi: redash
        app: redis 
        env: dev
        tier: database
    spec:
      volumes:
        - name: msp-invoice-redash-pv
          hostPath: 
            path: /tmp/redash
            type: DirectoryOrCreate
      containers:                
        - image: redis:3-alpine
          name: redashredis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              subPath: redash-redis
              name: msp-invoice-redash-pv
