apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30009
    - name: jvm-debug
      port: 8899
      targetPort: 8899
      nodePort: 30010
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: slesh/gateway:latest
          imagePullPolicy: Always
          env:
            - name: KEYCLOAK_CREDENTIALS_SECRET
              value: "61506e4a-5fef-4ce1-bc15-23dffc843344"
            - name: DB_CLICKHOUSE_URL
              value: "jdbc:clickhouse://clickhouse:8123/default"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://172.28.128.3:30008/auth/"
            - name: SERVER_PORT
              value: "8081"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: jvm-debug
              containerPort: 8899
              protocol: TCP