apiVersion: v1
kind: Service
metadata:
  labels:
    project: msp-invoice
    bi: apache-superset
    app: apache-superset 
    env: dev
    tier: backend
  name: apache-superset
spec:
  type: NodePort
  ports:
    - name: web-client
      port: 8088
      targetPort: 8088
      nodePort: 30001
      protocol: TCP
  selector:
    project: msp-invoice
    bi: apache-superset
    app: apache-superset 
    env: dev
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-superset
  labels:
    project: msp-invoice
    bi: apache-superset
    app: apache-superset 
    env: dev
    tier: backend
spec:
  selector:
    matchLabels:
      project: msp-invoice
      bi: apache-superset
      app: apache-superset 
      env: dev
      tier: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: msp-invoice
        bi: apache-superset
        app: apache-superset 
        env: dev
        tier: backend
    spec:
      volumes:
        - name: msp-invoice-pv
          hostPath: 
            path: /tmp
            type: DirectoryOrCreate
      containers:
        - name: apache-superset
          image: 'lansoftdev/apache-superset-clickhouse'
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8088
              protocol: TCP
          volumeMounts:
            - name: msp-invoice-pv
              mountPath: /app/superset_home
              subPath: superset_home