apiVersion: v1
kind: Service
metadata:
  labels:
    project: msp-invoice
    app: kaseya-proxy 
    env: dev
    tier: backend
  name: kaseya-proxy
spec:
  type: NodePort
  ports:
    - name: web
      port: 8090
      targetPort: 8090
      nodePort: 30006
      protocol: TCP
  selector:
    project: msp-invoice
    app: kaseya-proxy 
    env: dev
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaseya-proxy
  labels:
    project: msp-invoice
    app: kaseya-proxy 
    env: dev
    tier: backend
spec:
  selector:
    matchLabels:
      project: msp-invoice
      app: kaseya-proxy 
      env: dev
      tier: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: msp-invoice
        app: kaseya-proxy 
        env: dev
        tier: backend
    spec:
      containers:
        - name: kaseya-proxy
          image: slesh/eugenics:kaseya-proxy
          imagePullPolicy: Always
          env:
            - name: KASEYA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kaseya-user
                  key:  KASEYA_USERNAME
            - name: KASEYA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kaseya-user
                  key:  KASEYA_PASSWORD
          ports:
            - name: web
              containerPort: 8090
              protocol: TCP